name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: crawl
      run: |
        pip3 install -r requirements.txt
        scrapy crawl items -o qiita`date "+%Y%m%d"`.json -t jsonlines --nolog
        gsutil cp qiita`date "+%Y%m%d"`.json gs://vdslab/qiita/
        bq --project=vdslab-207906 --dataset_id=qiita mk items`date "+%Y%m%d"`
      env:
        QIITA_TOKEN:  ${{ secrets.QIITA_TOKEN }}
